# controller_manager:
#   ros__parameters:
#     update_rate: 1000  # Hz

#     joint_state_broadcaster:
#       type: joint_state_broadcaster/JointStateBroadcaster

# joint_trajectory_controller:
#   ros__parameters:
#     type: joint_trajectory_controller/JointTrajectoryController
#     joints:
#       - slider_to_cart
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity


# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true

    head_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    left_leg_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_leg_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

head_group_controller:
  ros__parameters:
    joints:
      - lower_neck_body_joint
      - upper_neck_lower_neck_joint
      - head_upper_neck_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
left_leg_group_controller:
  ros__parameters:
    joints:
      - left_upper_hip_body_joint
      - left_lower_hip_left_upper_hip_joint
      - left_upper_leg_left_lower_hip_joint
      - left_lower_leg_left_upper_leg_joint
      - left_foot_left_lower_leg_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
right_leg_group_controller:
  ros__parameters:
    joints:
      - right_upper_hip_body_joint
      - right_lower_hip_right_upper_hip_joint
      - right_upper_leg_right_lower_hip_joint
      - right_lower_leg_right_upper_leg_joint
      - right_foot_right_lower_leg_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity