# Default initial positions for shi2d2's ros2_control fake system

initial_positions:
  head_upper_neck_joint: 0
  left_foot_left_lower_leg_joint: 0
  left_lower_hip_left_upper_hip_joint: 0
  left_lower_leg_left_upper_leg_joint: 0
  left_upper_hip_body_joint: 0
  left_upper_leg_left_lower_hip_joint: 0
  lower_neck_body_joint: 0
  right_foot_right_lower_leg_joint: 0
  right_lower_hip_right_upper_hip_joint: 0
  right_lower_leg_right_upper_leg_joint: 0
  right_upper_hip_body_joint: 0
  right_upper_leg_right_lower_hip_joint: 0
  upper_neck_lower_neck_joint: 0