# ros2 run moveit_kinematics auto_create_ikfast_moveit_plugin.sh --iktype Translation3D shi2d2_model/urdf/shi2d2_model_ik.urdf left_leg_group left_upper_hip_link left_foot_link
# ros2 run moveit_kinematics auto_create_ikfast_moveit_plugin.sh --iktype Translation3D shi2d2_model/urdf/shi2d2_model_ik.urdf right_leg_group right_upper_hip_link right_foot_link
head_group:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.0050000000000000001
  kinematics_solver_timeout: 0.0050000000000000001
left_leg_group:
  kinematics_solver: shi2d2_left_leg_group_ikfast_plugin/IKFastKinematicsPlugin
  kinematics_solver_search_resolution: 0.0050000000000000001
  kinematics_solver_timeout: 0.0050000000000000001
right_leg_group:
  kinematics_solver: shi2d2_right_leg_group_ikfast_plugin/IKFastKinematicsPlugin
  kinematics_solver_search_resolution: 0.0050000000000000001
  kinematics_solver_timeout: 0.0050000000000000001