# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - head_group_controller
    - left_leg_group_controller
    - right_leg_group_controller

  head_group_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - lower_neck_body_joint
      - upper_neck_lower_neck_joint
      - head_upper_neck_joint
  left_leg_group_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - left_upper_hip_body_joint
      - left_lower_hip_left_upper_hip_joint
      - left_upper_leg_left_lower_hip_joint
      - left_lower_leg_left_upper_leg_joint
      - left_foot_left_lower_leg_joint
  right_leg_group_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - right_upper_hip_body_joint
      - right_lower_hip_right_upper_hip_joint
      - right_upper_leg_right_lower_hip_joint
      - right_lower_leg_right_upper_leg_joint
      - right_foot_right_lower_leg_joint